=  Polycode
Nils Ponsard <nils.ponsard@etu.umontpellier.fr>
19-10-2022
:reproducible:
:toc:


== 1 Functional quarter
=== Vocabulary 

* Admin : A privileged user that has CRUD access to all the data.
* User : Person that has a PolyCode account.
* Candidate : Person that participate to a test.
* Guest : Person that doesn't have a PolyCode account.
* Captain : Person that owns and manages a team.
* Assessment Creator : Person that can create assessments and manage them.
* Practice Creator : Person that can create contents, modules and manage them.
* Test : Ordered list of questions meant to evaluate a candidate.
* Campaign : Association of a group of candidate and a test.
* Question : Content that is used in a test.
* Module : A group of contents and other modules.
* Content : Coherent group of components that are organized in a tree structure.
* Component : Display element or interactive element in a content (example : code challenge, markdown information text).
* Hint : A piece of information that the user can buy to help him solve a problem (in a code challenge).
* PolyPoints : Virtual currency used to buy hints, earned by completing all submittables of contents and modules.
* Runner : Sandboxed environment that runs the code of the candidate.
* Submittable : Component that exposes a problem to solve. The user can submit a submission to solve the problem.
* Submission : User’s answer to a submittable, validated through a validator.
* Team : Group of users, teams are ranked in a leaderboard based of the total score of their members.
* Validator : Instructions to test the validity of a submission (example : for a specific input expect a specific output).
* Tag : Keyword that can be associated to a content or a module.


=== User stories

[cols="1,1,1"]
|===
|As a |I want to |So that

|Guest
|Create an account
|Use the features of the app

|User
|Update my emails
|Update my ways to recover my account, get important updates and notifications

|User
|Receive a welcome email after creating an account
|Know that my account has been created

|User
|Get information about my account
|Review my account information

|User
|Get info about another user 
|Know the user

|User
|Update my username, programming languages and short description
|Keep my information up to date

|User
|Delete my account
|Remove my data from the app

|User
|Log in to my account via email and password
|Access my account

|User
|Logout of my account
|Prevent unauthorized access to my account

|User 
|Reset my password
|Get access to my account if I forgot my password

|User
|Create a team 
|Participate to the team leaderboard an gather users

|Captain
|Invite users to my team
|Add users to my team

|Captain
|Kick users from my team
|Remove users from my team (inactive, problematic, etc.)

|Captain
|Give the captain role to another user
|Transfer the captain role to another user

|Captain
|Delete my team
|Remove my team from the app

|Captain
|Update info about my team
|Keep my team info up to date

|User
|Accept an invitation to a team
|Join a team

|User
|Leave a team
|cease to be associated to a team

|User
|Get info about a team, members, points, name, description
|Know the team

|User
|Get the leaderboard of teams
|Know the ranking of teams

|User
|Get the leaderboard of users in a team
|Know the ranking of users in a team

|User 
|Get the list of available content
|Know the content available

|User
|Get the list of available modules
|Know the modules available

|User
|Get the list of contents and submodules of a module
|Know how to complete a module

|User
|Get the latest modules and contents
|Know what have been added recently

|User
|Get the informations about a content
|Know the content

|User
|Get the informations about a module
|Know the module, the objectives 

|User
|Get the informations about a test
|Know the test, its objectives

|User
|Get the components of a content
|Get the informations the content aims to convey, it’s submittables

|User
|Submit a solution to a submittable component
|Validate my solution

|User
|Execute a validator on my code
|Validate my solution on a public validator

|User
|Get the last solution I submitted to a submittable component
|Get back to my solution and improve it

|User
|Write a solution to a submittable component in a code editor (for a code challenge)
|Write my solution and test it

|User
|Add new sources files to a code editor (for a code challenge)
|Split the code answer in multiple files

User,ajouter des fichiers dans l’éditeur (exercice),Organiser la solution en plusieurs fichiers
User,supprimer des fichiers dans l’éditeur,Organiser la solution en plusieurs fichiers
User,acheter des données de validateur (entrée + sortie) avec des PolyPoints ⇒ hint,comprendre mieux comment résoudre l’exercice
User,suivre ma progression dans chacun des modules,"Voir ce qui est complété / à faire "
User,voir le classement global des utilisateurs (par polypoints),Motivation à atteindre le sommet (principe de concurrence)
User,passer une évaluation,obtenir une certification
User,lire le contenu d’un cours,monter en compétence sur un sujet
Content Creator,"créer un exercice, et y ajouter du markdown, un code editor, un QCM organisé dans des conteneurs","Proposer l’apprentissage d’une nouvelle notion, faire vérifier la connaissance de cette notion par une question/ un code à écrire"
Content Creator,créer un module,Organiser les exercices par notion majeure / thématique
Assessment Creator,créer une évaluation,vérifier les compétence d’un utilisateur sur un contenu
Content Creator,ajouter ses exercices à un module qu’il a créé,remplir le contenu d’un module en ensemble d’élément cohérent
Content Creator,"ajouter des modules dans un module, et ce avec des modules qu’il a créé (sous-module)",remplir le contenu d’un module en ensemble d’élément cohérent
Content Creator,"modifier le nom, la description, le nombre de PolyPoints de récompense, les tags, le contenu (exercices et sous-module) de ses modules",Garder à jour un module
Content Creator,"modifier le titre, la description, le contenu, récompense en polypoints,  les validateurs, les tags d’un exercice",Garder à jour un exercice
Content Creator,"modifier le titre, la description, le contenu d’une évaluation",Garder à jour une évaluation
Content Creator,supprimer un exercice qu’il a créé,Réparer une erreur / ne plus vouloir la présence de ce contenu
Content Creator,supprimer un module qu’il a créé,Réparer une erreur / ne plus vouloir la présence de ce contenu
Content Creator,supprimer une évaluation qu’il a créé,Réparer une erreur / ne plus vouloir la présence de ce contenu
Content Creator,voir le résultat des utilisateurs sur une évaluation qu’il a créé,Pour que le recruteur / professeur voie le résultat des élèves pour attribuer une note / recruter
Admin,Promouvoir un utilisateur en rédacteur,qu’un utilisateur ai les droits d’un “redacteur”
Admin,Promouvoir un utilisateur en admin,qu’un utilisateur ai les droits d’un “admin”
Admin,Créer un utilisateur,Utiliser l’application avec un autre compte
Admin,Récupérer les données d’un utilisateur,Voir les informations confidentielles d’un compte utilisateur
Admin,Mettre à jour les données d’un utilisateur,Mettre à jour les informations personnelles afin qu’elles soient cohérentes
Admin,Supprimer un utilisateur,Ne plus donner accès à la plateforme pour un compte utilisateur
Admin,Créer un exercice,"Proposer l’apprentissage d’une nouvelle notion, faire vérifier la connaissance de cette notion par une question/ un code à écrire"
Admin,"modifier le titre, la description, le contenu, récompense en polypoints,  les validateurs, les tags d’un exercice",Garder à jour un exercice
Admin,Créer un module,Créer un module afin de regrouper des contenus
Admin,Récupérer les données d’un module,Voir les informations et les contenus associés à ce module
Admin,Mettre à jour les données d’un module,Garde le module à jour
Admin,Supprimer un module,Effacer les traces du module sur la plateforme
Admin,Créer une évaluation,vérifier les compétence d’un utilisateur sur un contenu
Admin,Récupérer les données d’une évaluation,Voir les différentes données en lien avec une évaluation
Admin,Mettre à jour les données d’une évaluation,Ajouter des utilisateurs ou modifier des données relatives à une évaluation
Admin,Supprimer une évaluation,Enlever une évaluation de la plateforme
Admin,Créer une team,Rassembler des utilisateurs dans une équipe
Admin,Ajouter un membre dans mon équipe,Proposer à un utilisateur de rejoindre mon équipe
Admin,Supprimer un membre d’une team,Enlever un utilisateur de mon équipe pour une quelconque raison
Admin,Supprimer une team,Supprimer une team qui ne valide pas les conditions d’utilisation
Admin,Modifier la description d’une équipe,Avoir une description à jour de l’équipe
Assessment Creator,créer une campagne de test,Evaluer le niveau des utilisateurs
Assessment Creator,ajouter des utilisateurs à ma campagne via une interface web,Faire participer les candidats
Assessment Creator,supprimer des utilisateurs à ma campagne via une interface web,Enlever un candidat des participants
Assessment Creator,ajouter des utilisateurs à ma campagne via des appels API,Faire participer les candidats
Assessment Creator,supprimer des utilisateurs à ma campagne via des appels API,Enlever un candidat des participants
Assessment Creator,ajouter des utilisateurs à ma campagne via l’importation de fichiers csv,Faire participer les candidats
Assessment Creator,voir les résultats et statistiques sur la campagne que j’ai créé,Me rendre compte du niveau des candidats testés
Assessment Creator,ajouter des tags à mes candidats,Grouper les candidats
Assessment Creator,définir une date limite pour ma campagne,Clôturer ma campagne à une date fixe
Candidate,revenir sur un test et reprendre là où j’en était,Finir mon test si jamais je quitte l’application
Assessment Creator,définir un temps limite pour chaque question de ma campagne,Les candidats répondent dans un temps limité
Assessment Creator,définir un nb de points pour chaque question,Avoir un score par candidats et voir leur différence de score à la fin de la campagne
Candidate,recevoir un mail me permettant de participer à une campagne de tests,Avoir un lien pour participer à une campagne
Candidate,Accepter de participer à une campagne,Tester ses compétences à travers une campagne
Candidate,Refuser de participer à une campagne,Avoir la possibilité de refuser une campagne et que le créateur en soit informé
Assessment Creator,"Éditer ma campagne, les tests liés",Modifier une campagne précédemment créée
Assessment Creator,Définir une date de début de ma campagne,"Définir une date pour les candidats, ainsi qu’un temps imparti pour finaliser la campagne"
Assessment creator,Envoyer des liens de ma campagne manuellement à mes candidats,S’assurer que les candidats reçoivent bien le lien pour participer à une campagne
Candidate,Recevoir un mail de confirmation contenant des stats quand j’ai soumis mon test,Notifier l’utilisateur que sa participation et ses réponses ont bien été enregistrées pour une campagne
Assessment Creator,Voir le nombre de points totaux par candidats,Comparer les points des candidats ayant participé à la campagne
Assessment Creator,Visualiser un graphique/un excel par tags de content et par candidats,Voir graphiquement les différents résultats
Assessment Creator,Exporter les résultats synthétisés dans un pdf,Sauvegarder les résultats des candidats et avoir une vue synthétique
Assessment Creator,Exporter les résultats détaillés dans un pdf,Sauvegarder les résultats des candidats et y avoir accès sans passer par l’application
Assessment Creator,Avoir une vue comparative des candidats sous la forme d’un tableau excel,Comparer les score des candidats à travers un tableau
Assessment Creator,"Trier la liste des candidats par tags, résultats",Comparer les résultats des candidats en fonction de données précises
Assessment Creator,"télécharger les scores des candidats ",afin de garder les stats en local

|===



== 2 Identification and OIDC

- Redirect from frontend
- callback to frontend
- frontend sends token to backend
- backend checks token with OIDC provider `https://${keycloakHost}:${keycloakPort}/auth/realms/${realmName}/protocol/openid-connect/userinfo`



- enable keycloak registration
- find user by email
- create user if it doesn’t exsist

If email is not found, check email verification, if verified create a new user, ask for confirmation of the username, accept the TOS.



== 3 Microservice communication

=== Environment variables

Each service requires environment variables indicating where to find the other services. 

This can become tedious to setup, these variables could have a default value corresponding to the usual service name in kubernetes.

=== service discovery

When starting the services register to the a server. This server will be able to provide the address of the other services.

Two ways to get the address of the other services:
- every time you need to do a request
- fetch regularly the list of services and store it to use for requests.


SPOF : if the service discovery is down, all services can’t reach eachother, you can still keep the previous adress in cache and update when back up.


== 4 Traceability and logging

=== Fetch the logs

- log everything to stdout or stderr
- use (or create) a log aggregator that reads the output from kube or the platform.


=== central logging server 
Let the services upload to a central server.

THIS IS A SPOF, but the project can run without it, you just won’t be able to troobleshoot errors when this service is down.

== 5 Search engine

=== Concept

See `./sketches/Q5-search/ui.drawio`.

This concept needs a new collection storing the search history of all users, containing the search query and the number of times it has been searched. The index will be on the query field (to search text).

When a user starts to type in the search field, the server will respond with suggestion of queries, matched by the beginning of the text, ordered by the number of times researched.

Selecting a suggestion fills the search field and validates the search.

Once the search is validated, use a fuzzy finding algorithm to search through the content 
TODO : strategy, explain fuzzi finding, find how to in mongo

All types of content (module, content, assignement) will be in a list of results, with the same presentation and the type marked.

Ordering with points :
* 1 point for each matching word in the description
* 2 point for each matching word in the title
* 3 point for each matching word in the tags

Results ordered by points, then by date of creation (default, can be changed to date then points).


=== Implementation

[source,JavaScript]
----
db.blog.createIndex(
   {
     description: "text",
     tags: "text",
     title: "text"
   },
   {
     weights: {
      description: 10,
      title: 20,
      tags: 30
     },
     name: "TextIndex"
   }
 )
----


search  :

[source,JavaScript]
----
db.stores.find(
   { $text: { $search: "rust in 30 days" } },
   { score: { $meta: "textScore" } }
).sort( { score: { $meta: "textScore" } } )
----






== 6 Runner architecture

=== Runner definition

A runner is a service used to run code sent by the user in a sandboxed environment. It feeds data to the stdin of the programs and returns the stdout and stderr.

Validity of the solution can be checked by sending specific inputs to stdin and checking if the output corresponds to the expected output.

=== Execution isolation 

To negate the effect of malicious code, the user submitted code should not have arbitrary file system and memory access, internet access, host system access. The running program should also be limited in CPU and memory usage to prevent denial of service attacks.

=== Virtal machine architecture 

TODO

LXC ?

=== Runner registration 

- Generate a token from the service managing the runners
- Launch the runner program on a machine providing the token and the address of the runner manager
- Periodically the runner will send a request to the runner manager to retrieve new jobs to run
- The runner manager send some jobs to the runner, the number of jobs depending on the capacity of the runner (CPU, RAM) and the number of runners available to the manager
- The runner runs the jobs 
- When a job finishes the runner does a request to the manager to send the result of the job


== 7 Data architecture

=== current data 

- postgresql 
- mongodb

== 8 Mobile app

=== Functionnalities

- Read courses
- Download courses/videos for offline use
- Answer to MCQ questions
- browse courses/exercises
- manage accounte
- notification on new content in a module ?


=== Authentication 

Oauth2 ? open web page with token in url


== 9 Microservice security

- HTTPS + certificate exchange (kube secrets).

== 10 UI microservice

Iframe ?
-> explorer Remix et Next.js 13
